version: '3.6'

networks:
  vezadocker:

services:
  php:
    container_name: php_veza
    build:
      context: .
      dockerfile: .docker/Dockerfile
    working_dir: /app/veza
    container_name: php_${DB_DATABASE}
    volumes:
      - .:/app/veza
    ports:
      - "9000:9000"
    environment:
      DB_HOST: mysql
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - vezadocker

  nginx:
    image: nginx:1.17
    container_name: nginx_${DB_DATABASE}
    ports:
      - 8000:80
      - 8001:443
    volumes:
      - .:/app/veza
      - ./.docker/.nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/.nginx/veza-app.crt:/etc/nginx/veza-app.crt
      - ./.docker/.nginx/veza-app.key:/etc/nginx/veza-app.key
    networks:
      - vezadocker

  mysql:
    image: mysql:5.7
    container_name: mysql_${DB_DATABASE}
    ports:
      - 3306:3306
    tty: true
    depends_on:
      - php
    volumes:
      - .:/app/veza
      - ./.docker/.mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - vezadocker

  phpadmin:
    image: phpmyadmin/phpmyadmin:5.0
    container_name: phpadmin_${DB_DATABASE}
    ports:
      - 8080:80
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - vezadocker

# ------------------- OPTIONAL --------------------- #
  composer:
    image: composer:1.9
    container_name: composer_${DB_DATABASE}
    tty: true
    depends_on:
      - php
    working_dir: /app/veza
    volumes:
      - .:/app/veza
    # command tail -F is added so container won't exit
    command: sh -c "composer install -n && tail -F /anything/here"
    networks:
      - vezadocker

  node:
    image: node:13.6-alpine
    container_name: node_${DB_DATABASE}
    tty: true
    depends_on:
      - php
    working_dir: /app/veza
    volumes:
      - .:/app/veza
    # command tail -F is added so container won't exit
    # command: sh -c "npm install --prefer-offline --no-audit && tail -F /anything/here"
    command: sh -c "yarn install && tail -F /anything/here"
    networks:
      - vezadocker
# ------------------ OPTIONAL --------------------- #
